### ISSUE TITLE
Switch to go module

### ISSUE THREAD

**Issue by 0xjac** [turnkey-commerce/gendal#12]
`gendal` is still using [dep](https://github.com/golang/dep).

It would be great to move to go modules.

I have the code ready and I'd be happy to submit a PR, but it is based on top of #10 and #11.
Do you prefer a PR with all 3 or shall I wait for you to merge those first.

You can have a look at the changes [here](https://github.com/0xjac/gendal/commit/01c00f3be26dd53ed90b8e3896bed330978cb65c).

> Note: I am not fully familiar with deps/go mod yet, so any feedback is welcome.

**Comment by turnkey-commerce** [comment]
I am OK with it and do have experience with go modules and have been meaning to do the same. I'll merge the other PR's shortly and then please go ahead and submit the PR.

**Comment by turnkey-commerce** [comment]
@0xjac I checked your changes and they look good so please submit your PR when ready.

**Comment by 0xjac** [comment]
@turnkey-commerce That was quick, thanks a lot, submitted (#13)

I don't have much experience with the the vendor part. Please review carefully and let me know if anything needs changing.

**Comment by turnkey-commerce** [comment]
Vendoring is optional with go mod but I noticed if you run the go install command you have to use this type of argument for it to force it to use the vendor path:

`
go install -mod=vendor
`

I thought about removing the vendor but like it to avoid issues with some random thing on the net for reproducible builds. In my testing the builds work either way so think how you did it is fine.

**Comment by turnkey-commerce** [comment]
Also testing the exe built by both methods worked fine for me.

Thanks for your PR!
