### ISSUE TITLE
Release a new version with #18

### ISSUE THREAD

**Issue by megaturbo** [turnkey-commerce/gendal#19]
Hey, we would be really pleased to use #18 in our project so for now we stick to commit version 13b932a but it would be cleaner on our side to point to a specific release version number.

Do you think it's possible to release a new version of gendal containing those changes ?

Thank you very much for your work.

**Comment by turnkey-commerce** [comment]
Certainly @megaturbo, have been meaning to do that anyway and will take care of it very shortly.

**Comment by turnkey-commerce** [comment]
Available now as release [v1.2.3](https://github.com/turnkey-commerce/gendal/tree/v1.2.3).
