### ISSUE TITLE
Updating gendal with go get fails

### ISSUE THREAD

**Issue by 0xjac** [turnkey-commerce/gendal#30]
When updating gendal, it fails because of a renamed dependency:

``` shell
$ go get -u github.com/turnkey-commerce/gendal
go get: github.com/knq/snaker@v0.0.0-20181215144011-2bc8a4db4687 updating to
	github.com/knq/snaker@v0.1.6: parsing go.mod:
	module declares its path as: github.com/kenshaw/snaker
	        but was required as: github.com/knq/snaker
```

This is due to `github.com/knq/snaker` which [changed its name to `github.com/kenshaw/snaker` on 2021-07-30 (7 days ago...)](https://github.com/kenshaw/snaker/commit/fbe733f1d0c64dc1ee9b3fa0382286f347e8e137).

**Comment by 0xjac** [comment]
@turnkey-commerce happy to submit a PR for this if you want!

**Comment by turnkey-commerce** [comment]
@0xjac please do, thanks.

**Comment by turnkey-commerce** [comment]
@0xjac, never mind I can do this change since am working on the PR now.
