### ISSUE TITLE
Cockroachdb Foreign Key Generation Not Always Working

### ISSUE THREAD

**Issue by TravisS25** [turnkey-commerce/gendal#7]
I'm currently using the cockroachdb connection string against my cockroach db and during generation the foreignkey.go.tpl does not always generate all foreignkey relationship functions from the table.  I have tested this on the postgres connection string against my postgres db and it works every time but going through cockroach it appears to be very random, sometimes it's generating half the foreignkey functions, sometimes 80% of them and sometimes all of them.

Anyone else using cockroachdb and getting this random behavior?

**Comment by turnkey-commerce** [comment]
That is very weird indeed, sounds almost like a race condition. I can't think of anything that would cause that offhand. Good idea to test the schema on postgres -- the generation code is the same except for how the autoincrements are handled for the primary keys.
